### ISSUE TITLE
Add description of delayed AFC task to datasets

### ISSUE THREAD

**Issue by shauld** [zqwei/Neural-Recording-Methodology-Comparison-Website#19]
Add brief description of the task. Have it collapsable so it initially isn't displayed. A fancier way would be to have a Wiki that defines terms, that way it will be cleaner and a click away from the datasets sections, instead of collapsed and in it, but that may be overkill.

**Comment by shauld** [comment]
Or instead of a Wiki we can just add a "Glossary" section of the site and define these terms there.

**Comment by shauld** [comment]
Do you think a Glossary section is a good solution?

**Comment by zqwei** [comment]
how about popout, like we used in sim-ephys-imaging table?


![](https://files.slack.com/files-pri/T1W5Q6223-F6SCTHLAD/screen_shot_2017-08-23_at_10.41.40_pm.png)

**Comment by shauld** [comment]
I think it might be hard to fit everything you want to say about the task into a popout (you would probably want a figure with the epochs and so on). There could be a popout that gives a very short description and links into the Glossary. Alternatively, we could just have a brief popout and add a link to a paper and figure

**Comment by zqwei** [comment]
I just understand what you mean here. I thought you want to explain some of the word/phase in dataset description. We definitely need to use accordion for large paragraph descriptions. But what I suggest some glossies in the description can be animated as pop-out.
